version: '3.8'

services:
  frontend:
    container_name: app-prod-conteneur
    image: diambarsene/jcaisse-frontend-app-react:latest # Remplacez par le nom et la version de votre image
    restart: always
    ports:
      - "8081:80" # Utilisez le port que vous souhaitez exposer
    environment:
      REACT_APP_API_URL_PARAMETRE: http://app-parametres-api:8084 # Remplacez par l'URL de votre API backend
      REACT_APP_API_URL_UTILISATEUR: http://app-users-api:8083
    depends_on:
      - app-parametres-api
      - app-users-api




#volumes:
  #parametres-db-data:
  #users-db-data:



# #profil dev
# version: "3.8"

# services:
#   app:
#     container_name: app-dev
#     image: app-dev
#     build:
#       target: development
#     volumes:
#       - ./src:/app/src
#     ports:
#       - 3000:3000


# #profil prod
# version: "3.8"

# services:
#   app:
#     container_name: app-prod
#     image: app-prod
#     build:
#       target: production